from __future__ import annotations

import json
import unittest
from pathlib import Path

from scripts import check_living_docs_hygiene as hygiene


ROOT = Path(__file__).resolve().parents[1]


class LivingDocsHygieneTests(unittest.TestCase):
    def test_hygiene_checker_passes(self):
        self.assertEqual(hygiene.check_living_docs_hygiene(), [])

    def test_core_living_docs_exist_and_are_indexed(self):
        docs_index = (ROOT / "docs" / "index.md").read_text(encoding="utf-8")

        for relative_path in hygiene.CORE_LIVING_DOCS:
            with self.subTest(relative_path=relative_path):
                self.assertTrue((ROOT / relative_path).exists())
                if relative_path != "docs/index.md":
                    self.assertIn(Path(relative_path).name, docs_index)

    def test_generated_artifacts_have_commands_and_runtime_boundaries(self):
        package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
        scripts = package["scripts"]
        verify_docs = scripts["verify:docs"]

        for artifact in hygiene.GENERATED_ARTIFACTS:
            with self.subTest(path=artifact.path):
                artifact_path = ROOT / artifact.path
                self.assertTrue(artifact_path.exists())
                self.assertIn(artifact.command, scripts)
                self.assertIn(artifact.generator, scripts[artifact.command])
                self.assertIn(artifact.generator, verify_docs)

                if artifact.artifact_type == "json":
                    payload = json.loads(artifact_path.read_text(encoding="utf-8"))
                    self.assertEqual(payload["generated_by"], artifact.generator)
                    if artifact.runtime_use_false:
                        self.assertFalse(payload["runtime_use"])
                else:
                    source = artifact_path.read_text(encoding="utf-8")
                    self.assertIn("Generated by", source)
                    self.assertIn(artifact.generator, source)
                    self.assertTrue("Do not hand-edit" in source or "Edit the generator" in source)

    def test_source_of_truth_boundary_is_visible(self):
        for relative_path in hygiene.SOURCE_OF_TRUTH_DOCS:
            with self.subTest(relative_path=relative_path):
                text = (ROOT / relative_path).read_text(encoding="utf-8").lower()
                self.assertTrue("source of truth" in text or "source-of-truth" in text)
                self.assertTrue("evidence record" in text or "records" in text)

    def test_docs_ownership_markers_are_not_placeholders(self):
        for relative_path in hygiene.CORE_LIVING_DOCS:
            with self.subTest(relative_path=relative_path):
                text = (ROOT / relative_path).read_text(encoding="utf-8")
                self.assertIsNone(hygiene.PLACEHOLDER_PATTERN.search(text))

        next_steps = (ROOT / "docs" / "NEXT_STEPS.md").read_text(encoding="utf-8")
        worklog = (ROOT / "docs" / "WORKLOG.md").read_text(encoding="utf-8")
        decisions = (ROOT / "docs" / "DECISIONS.md").read_text(encoding="utf-8")
        self.assertRegex(next_steps, r"(?m)^Last updated:\s+\d{4}-\d{2}-\d{2}$")
        self.assertRegex(worklog, r"(?m)^##\s+\d{4}-\d{2}-\d{2}$")
        self.assertIn("Durable decision:", decisions)


if __name__ == "__main__":
    unittest.main()
