const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const vm = require("node:vm");
const ts = require("typescript");

const ROOT = path.join(__dirname, "..", "..");

function readRepoFile(relativePath) {
  return fs.readFileSync(path.join(ROOT, relativePath), "utf8");
}

function loadTsModule(relativePath) {
  const sourcePath = path.join(ROOT, relativePath);
  const source = fs.readFileSync(sourcePath, "utf8");
  const transpiled = ts.transpileModule(source, {
    compilerOptions: {
      esModuleInterop: true,
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
    },
    fileName: sourcePath,
  }).outputText;
  const module = { exports: {} };
  vm.runInNewContext(
    transpiled,
    { console, exports: module.exports, module, require },
    { filename: sourcePath }
  );
  return module.exports;
}

function plain(value) {
  return JSON.parse(JSON.stringify(value));
}

test("generated frontend proof contract matches versioned JSON source", () => {
  const sourceContract = JSON.parse(readRepoFile("data/contracts/proof-evidence-contract.json"));
  const generated = loadTsModule("src/lib/generated/proofEvidenceContract.ts");

  assert.equal(generated.PROOF_EVIDENCE_CONTRACT_VERSION, sourceContract.version);
  assert.deepEqual(plain(generated.PROOF_EVIDENCE_CONTRACT), sourceContract);
});

test("generated frontend proof contract carries ownership banner", () => {
  const generatedSource = readRepoFile("src/lib/generated/proofEvidenceContract.ts");

  assert.match(generatedSource, /Generated by scripts\/generate_proof_evidence_contract\.py/);
  assert.match(generatedSource, /Source: data\/contracts\/proof-evidence-contract\.json/);
  assert.match(generatedSource, /Do not hand-edit/);
});

test("frontend proof facade imports generated artifact, not JSON directly", () => {
  const facade = readRepoFile("src/lib/trading-desk/proofContract.ts");
  const evidence = readRepoFile("src/lib/trading-desk/positionEvidence.ts");

  assert.match(facade, /@\/lib\/generated\/proofEvidenceContract/);
  assert.doesNotMatch(facade, /proof-evidence-contract\.json/);
  assert.match(evidence, /@\/lib\/trading-desk\/proofContract/);
  assert.doesNotMatch(evidence, /@\/lib\/generated\/proofEvidenceContract/);
});
