from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "data" / "contracts" / "proof-invariant-cases.json"
OUTPUT_PATH = ROOT / "docs" / "proof-invariant-table.md"


def _load_manifest() -> dict[str, Any]:
    return json.loads(SOURCE_PATH.read_text(encoding="utf-8"))


def _yes(value: Any) -> str:
    return "yes" if bool(value) else "no"


def _cell(value: Any) -> str:
    return str(value if value is not None else "").replace("|", "\\|")


def _render_markdown(manifest: dict[str, Any]) -> str:
    cases = list(manifest.get("cases") or [])
    lines = [
        "# Proof Invariant Table",
        "",
        "Generated by `scripts/generate_proof_invariant_table.py`.",
        "Source: `data/contracts/proof-invariant-cases.json`.",
        "Runtime use: `false`.",
        "Do not hand-edit; run `npm run docs:proof-invariant-table`.",
        "",
        "This table is a regression and orientation artifact for proof/evidence claims. It does not define runtime behavior; backend predicates remain owned by `python-backend/proof_contract.py`, and frontend display/filter predicates remain owned by `src/lib/trading-desk/positionEvidence.ts`.",
        "",
        "## Scope",
        "",
        _cell(manifest.get("scope")),
        "",
        "## Cases",
        "",
        "| Case | Description | Raw exact | Backend production proof | Backend proof-grade closed | Frontend group | Frontend production proof | Truth-grade closed | Realized P&L closed | Notes |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for case in cases:
        expected = case["expected"]
        backend = expected["backend"]
        frontend = expected["frontend"]
        lines.append(
            " | ".join(
                [
                    f"| `{_cell(case['id'])}`",
                    _cell(case["description"]),
                    _yes(backend["raw_exact_contract"]),
                    _yes(backend["production_proof"]),
                    _yes(backend["proof_grade_exact_closed"]),
                    f"`{_cell(frontend['evidence_group'])}`",
                    _yes(frontend["production_proof"]),
                    _yes(frontend["truth_grade_closed"]),
                    _yes(frontend["realized_pnl_closed"]),
                    _cell(case.get("notes", "")) + " |",
                ]
            )
        )

    lines.extend(["", "## Non-Goals", ""])
    for non_goal in manifest.get("non_goals") or []:
        lines.append(f"- {_cell(non_goal)}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the proof invariant table documentation.")
    parser.add_argument("--check", action="store_true", help="Fail if the generated Markdown is stale.")
    args = parser.parse_args()

    rendered = _render_markdown(_load_manifest())
    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH.relative_to(ROOT)} is missing; run this script without --check.", file=sys.stderr)
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
            print(f"{OUTPUT_PATH.relative_to(ROOT)} is out of date; run this script without --check.", file=sys.stderr)
            return 1
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
