from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "data" / "contracts" / "forward-holdout-contract.json"
DOC_PATH = ROOT / "docs" / "forward-holdout-contract.md"


def build_contract() -> dict[str, Any]:
    return {
        "contract_id": "forward-holdout-contract",
        "version": 1,
        "status": "active",
        "runtime_use": False,
        "last_updated": "2026-06-14",
        "generated_by": "scripts/generate_forward_holdout_contract.py",
        "scope": "regular_options_autoresearch",
        "protected_range": {
            "start_date": "2026-06-05",
            "end_date": None,
            "date_basis": "candidate_entry_date",
            "timezone": "America/New_York",
            "source_evidence": [
                "docs/PROJECT_CONTEXT.md regular profit-loop intraday repair note",
                "docs/NEXT_STEPS.md forward-holdout strict canary note",
                "data/options-validation/runs/20260605_022559_broad_intraday.json",
            ],
            "rationale": (
                "Dates after the repaired intraday proof artifact are reserved for fresh forward validation "
                "and must not be consumed by ordinary autoresearch experiments."
            ),
        },
        "policy": {
            "normal_experiments": "refuse_any_replay_window_overlapping_the_protected_range",
            "champion_final_eval": {
                "flag": "--champion-final-eval",
                "allowed": True,
                "limit": "one_consumption_per_strategy_family_ever",
                "variant_limit": 1,
                "ledger_append_required": True,
                "ledger_path": "data/profitability-lab/regular-options-autoresearch/ledger.jsonl",
                "ledger_marker": "holdout_consumption.consumed=true",
            },
            "proof_bars": "unchanged",
            "scanner_policy": "unchanged",
            "broker_behavior": "unchanged",
        },
        "enforcement": {
            "harness": "scripts/run_regular_options_goal_experiment.py",
            "refusal_timing": "before_lane_variant_replay",
            "strategy_family_source": "scripts/evaluate_regular_options_autoresearch.py infer_strategy_family",
        },
        "non_goals": [
            "does_not_lower_existing_promotion_bars",
            "does_not_turn_holdout_rows_into_production_proof",
            "does_not_submit_or_change_broker_orders",
            "does_not_change_scanner_guardrails",
        ],
    }


def render_markdown(contract: dict[str, Any]) -> str:
    protected = contract["protected_range"]
    champion = contract["policy"]["champion_final_eval"]
    lines = [
        "# Forward Holdout Contract",
        "",
        "Generated by `scripts/generate_forward_holdout_contract.py`. Do not hand-edit this file.",
        "",
        "Runtime use: `false`.",
        "JSON sibling: `data/contracts/forward-holdout-contract.json`.",
        "",
        f"- Contract id: `{contract['contract_id']}`",
        f"- Version: `{contract['version']}`",
        f"- Status: `{contract['status']}`",
        f"- Last updated: `{contract['last_updated']}`",
        f"- Scope: `{contract['scope']}`",
        f"- Generated by: `{contract['generated_by']}`",
        "",
        "## Protected Range",
        "",
        f"- Start date: `{protected['start_date']}`",
        f"- End date: `{protected['end_date'] or 'open'}`",
        f"- Date basis: `{protected['date_basis']}`",
        f"- Timezone: `{protected['timezone']}`",
        f"- Rationale: {protected['rationale']}",
        "",
        "## Enforcement",
        "",
        f"- Harness: `{contract['enforcement']['harness']}`",
        f"- Refusal timing: `{contract['enforcement']['refusal_timing']}`",
        f"- Normal experiments: `{contract['policy']['normal_experiments']}`",
        f"- Champion flag: `{champion['flag']}`",
        f"- Champion limit: `{champion['limit']}`",
        f"- Variant limit: `{champion['variant_limit']}`",
        f"- Ledger append required: `{champion['ledger_append_required']}`",
        f"- Ledger path: `{champion['ledger_path']}`",
        f"- Ledger marker: `{champion['ledger_marker']}`",
        "",
        "## Unchanged Rules",
        "",
        f"- Proof bars: `{contract['policy']['proof_bars']}`",
        f"- Scanner policy: `{contract['policy']['scanner_policy']}`",
        f"- Broker behavior: `{contract['policy']['broker_behavior']}`",
        "",
        "## Source Evidence",
        "",
    ]
    lines.extend(f"- `{item}`" for item in protected["source_evidence"])
    lines.extend(
        [
            "",
            "## Non-Goals",
            "",
        ]
    )
    lines.extend(f"- `{item}`" for item in contract["non_goals"])
    return "\n".join(lines).rstrip() + "\n"


def _json_text(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def write_outputs() -> dict[str, str]:
    contract = build_contract()
    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_text(_json_text(contract), encoding="utf8")
    DOC_PATH.write_text(render_markdown(contract), encoding="utf8")
    return {"contract": str(CONTRACT_PATH), "doc": str(DOC_PATH)}


def check_outputs() -> list[str]:
    contract = build_contract()
    expected = {
        CONTRACT_PATH: _json_text(contract),
        DOC_PATH: render_markdown(contract),
    }
    failures: list[str] = []
    for path, text in expected.items():
        if not path.exists():
            failures.append(f"missing {path.relative_to(ROOT)}")
            continue
        if path.read_text(encoding="utf8") != text:
            failures.append(f"stale {path.relative_to(ROOT)}")
    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the regular-options forward holdout contract.")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.check:
        failures = check_outputs()
        if failures:
            print("\n".join(failures), file=sys.stderr)
            return 1
        return 0
    print(json.dumps(write_outputs(), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
