from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "data" / "contracts" / "proof-evidence-contract.json"
OUTPUT_PATH = ROOT / "src" / "lib" / "generated" / "proofEvidenceContract.ts"


def _load_contract() -> dict[str, Any]:
    return json.loads(SOURCE_PATH.read_text(encoding="utf-8"))


def _render_contract(contract: dict[str, Any]) -> str:
    version = contract.get("version")
    if not isinstance(version, int):
        raise ValueError("proof-evidence-contract.json must declare an integer version")
    serialized = json.dumps(contract, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/generate_proof_evidence_contract.py.\n"
        "// Source: data/contracts/proof-evidence-contract.json.\n"
        "// Do not hand-edit.\n\n"
        f"export const PROOF_EVIDENCE_CONTRACT_VERSION = {version} as const;\n\n"
        f"export const PROOF_EVIDENCE_CONTRACT = {serialized} as const;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the frontend proof evidence contract TS artifact.")
    parser.add_argument("--check", action="store_true", help="Fail if the generated artifact is stale.")
    args = parser.parse_args()

    rendered = _render_contract(_load_contract())
    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH.relative_to(ROOT)} is missing; run this script without --check.", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{OUTPUT_PATH.relative_to(ROOT)} is out of date; run this script without --check.", file=sys.stderr)
            return 1
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
